### ISSUE TITLE
Are further versions as 1.20.2 planned?

### ISSUE THREAD

**Issue by sternschnaube** [SpaceWalkerRS/kabo-village-marker#1]
And does the mod works server-side, means Vanilla can connect without problems if the mod is not present?

Thank you for mainting the mod, I remember it from old days 😊

**Comment by SpaceWalkerRS** [comment]
Villager mechanics were completely overhauled in 1.14, removing the concept of 'villages', so this mod will not support any Minecraft version past 1.13.2.

The mod does work client side and server side. If you're in multiplayer, both the client and server will need the mod for you to get any functionality from it. 

If the server has the mod, Vanilla clients can safely connect. The mod will only send packets to clients that also have the mod.

**Comment by venaminecraft** [comment]
I totally ignored / not thought about the villager changes. Thanks!
